# Generated by Django 2.2 on 2020-11-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201124_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profilepic.jpg', upload_to='pictures'),
        ),
    ]
