# Generated by Django 2.2 on 2020-11-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201127_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(default='cooking', max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media',
            field=models.URLField(default='facebook.com'),
        ),
    ]
