# Generated by Django 2.2 on 2020-12-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201128_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_media',
        ),
    ]
