# Generated by Django 2.2 on 2020-12-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCookbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='cart',
        ),
    ]
