# Generated by Django 2.2 on 2020-12-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCookbook', '0003_auto_20201207_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_item', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='Enter Instructions'),
        ),
    ]
