# Generated by Django 2.2 on 2020-12-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCookbook', '0004_auto_20201207_1606'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoppinglist',
            table='shoppinglist',
        ),
    ]
