# Generated by Django 2.2 on 2020-12-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCookbook', '0005_auto_20201207_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipe_placeholder.jpg', upload_to='pictures'),
        ),
    ]
